name: urleso-web

services:
  urleso.web:
    container_name: urleso-web
    build:
      context: .
      dockerfile: src/Urleso.Web.Service/Dockerfile
    image: urleso.web:latest
    environment:
      - Api__BaseAddress=${API_BASE_ADDRESS:-http://localhost:6800/}
    ports:
      - ${WEB_PORT}:8080
