<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <Version>0.1.0</Version>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Yarp.ReverseProxy"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Urleso.Web\Urleso.Web.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

</Project>
