server {
    listen 8080;

    root /usr/share/nginx/html;
    index index.html;

    # serve the precompressed *.gz files produced by dotnet publish
    gzip_static on;
    gzip on;
    gzip_types text/css application/javascript application/json application/wasm image/x-icon;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
