<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <ItemGroup>
        <PackageReference Include="FluentResults"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly"/>
        <PackageReference Include="MudBlazor"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Urleso.Api.Client\Urleso.Api.Client.csproj"/>
    </ItemGroup>

</Project>
